[package]
edition = "2021"
name = "trid"
version = "0.2.0-alpha"
description = "Turkish citizenship ID number type"
readme = "README.md"
homepage = "https://github.com/ssg/trid"
authors = ["Sedat Kapanoglu <sedat@kapanoglu.com>"]
license = "Apache-2.0"