name: Publish

on:
  push:
    branches: ["release"]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: cargo test --verbose
    - name: Publish
      run: cargo publish --verbose --token ${CARGO_REGISTRY_TOKEN}
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
